backend:
  name: github
  repo: dirkcuys/capewinelandstrailer
  branch: gh-pages
  collections:
    - name: 'pages'
      label: 'Pages'
      editor:
        preview: false
      files:
        - label: 'Landing page'
          name: 'index'
          file: 'index.md'
          fields:
            - label: 'Header carousel'
              name: 'header_carousel'
              widget: list
              fields:
                - { label: 'Image', name: 'image', widget: 'image'}
                - { label: 'Caption', name: 'caption', widget: 'markdown', required: false }
            - label: 'Sections'
              name: 'sections'
              widget: list
              fields:
                - { label: 'Section title', name: 'title', widget: 'string' }
                - label: 'Section items'
                  name: 'items' 
                  widget: list
                  fields:
                    - { label: 'Image', name: 'image', widget: 'image'}
                    - { label: 'Caption', name: 'caption', widget: 'markdown', required: false }
                    - { label: 'Link', name: 'link', widget: 'url', required: false }
